export const data = {
  experience: {
    p1: "I'm currently working as a fully remote QA Engineer at ChowNow. I spend most of my time working within a squad of developers and product/project managers to ensure we ship high quality software so that the local restaurants we serve can continue to thrive. On a daily basis I work with Python (Django), JavaScript, Postman, Cypress and several other tools. Our work with external partners has given me familiarity with APIs from Uber, DoorDash and others. Not only do I work towards finding bugs in our products, but I strive to find the root cause and work with others to find the best potential solutions.",
    p2: "Prior to ChowNow I worked as a Software Development Engineer in Test at Axos Bank in San Diego, working mainly on test automation with JavaScript. During my first few months at the bank I established myself as a leader within the testing team. I took the initiative to expand on our automation framework, Testim.io, by building out a Node.js/Express API that fed our testing data into an Elasticsearch cluster. Within Elasticsearch I then visualized the data using Kibana, so internal teams could see how their applications were performaing in both production and test environments. In addition to gathering data on applications, I also created a pipeline to ingest metadata from the testing framework itself, allowing the team to see how efficiently we were using it.",
    p3: "In my free time I enjoy coding full-stack web applications. I regularly work with React, Node.js, SQL and NoSQL Databases (mainly Postgres & MongoDB), REST & GraphQL APIs, and of course HTML & CSS. I've recently branched out on the front-end - I picked up Vue fairly quickly and started working with Svelte (which is what I rebuilt this site with!), as well as the back-end - I've been refactoring my 'Find Your Park' app from a REST to a GraphQL API. In addition to the web, I've published a mobile version of one of my apps to Apple's app store using React Native, and I have another in production.",
    p4: "I genuinely love to program - creating something from nothing is just awesome. On the other hand, digging deep into somebody elses code to figure out how it works or to troubleshoot a problem is equally rewarding. I find the process of learning new technologies both exciting and humbling - the software development field has a way of telling you how little you truly know and how much more knowledge there will always be to gain.",
    p5: "**Fun Fact:** I worked for nearly 5 years as a 911 Emergency Dispatcher. This experience has taught me how to be an oustanding communicator with both co-workers and the public, as well as how to remain calm and deliver results under stressful circumstances.",
  },
};
